/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const PlanType = IDL.Variant({
  'pro' : IDL.Null,
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'createdAt' : Time,
  'plan' : PlanType,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
});
export const ToolUsageStats = IDL.Record({
  'count' : IDL.Nat,
  'toolName' : IDL.Text,
});
export const SavedContent = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'toolName' : IDL.Text,
});
export const UserStats = IDL.Record({
  'totalUsage' : IDL.Nat,
  'profile' : UserProfile,
  'savedContentCount' : IDL.Nat,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteContent' : IDL.Func([IDL.Text], [], []),
  'favoriteTool' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavoriteTools' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPlan' : IDL.Func([], [IDL.Opt(PlanType)], ['query']),
  'getPlatformToolUsageStats' : IDL.Func(
      [],
      [IDL.Vec(ToolUsageStats)],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getSavedContent' : IDL.Func([], [IDL.Vec(SavedContent)], ['query']),
  'getSavedContentCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getToolUsageCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getTotalUsageStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'breakdown' : IDL.Vec(ToolUsageStats),
          'totalUses' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTotalUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserStats)], ['query']),
  'listContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'recordToolUsage' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveContent' : IDL.Func([SavedContent], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'unfavoriteTool' : IDL.Func([IDL.Text], [], []),
  'updatePlan' : IDL.Func([PlanType], [], []),
  'updateProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const PlanType = IDL.Variant({
    'pro' : IDL.Null,
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'createdAt' : Time,
    'plan' : PlanType,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  const ToolUsageStats = IDL.Record({
    'count' : IDL.Nat,
    'toolName' : IDL.Text,
  });
  const SavedContent = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'toolName' : IDL.Text,
  });
  const UserStats = IDL.Record({
    'totalUsage' : IDL.Nat,
    'profile' : UserProfile,
    'savedContentCount' : IDL.Nat,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteContent' : IDL.Func([IDL.Text], [], []),
    'favoriteTool' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavoriteTools' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPlan' : IDL.Func([], [IDL.Opt(PlanType)], ['query']),
    'getPlatformToolUsageStats' : IDL.Func(
        [],
        [IDL.Vec(ToolUsageStats)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getSavedContent' : IDL.Func([], [IDL.Vec(SavedContent)], ['query']),
    'getSavedContentCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getToolUsageCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getTotalUsageStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'breakdown' : IDL.Vec(ToolUsageStats),
            'totalUses' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTotalUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserStats)], ['query']),
    'listContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'recordToolUsage' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveContent' : IDL.Func([SavedContent], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'unfavoriteTool' : IDL.Func([IDL.Text], [], []),
    'updatePlan' : IDL.Func([PlanType], [], []),
    'updateProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };