/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type PlanType = { 'pro' : null } |
  { 'premium' : null } |
  { 'free' : null };
export interface SavedContent {
  'id' : string,
  'content' : string,
  'owner' : Principal,
  'createdAt' : Time,
  'tags' : Array<string>,
  'toolName' : string,
}
export type Time = bigint;
export interface ToolUsageStats { 'count' : bigint, 'toolName' : string }
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'createdAt' : Time,
  'plan' : PlanType,
  'email' : string,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'totalUsage' : bigint,
  'profile' : UserProfile,
  'savedContentCount' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteContent' : ActorMethod<[string], undefined>,
  'favoriteTool' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavoriteTools' : ActorMethod<[], Array<string>>,
  'getPlan' : ActorMethod<[], [] | [PlanType]>,
  'getPlatformToolUsageStats' : ActorMethod<[], Array<ToolUsageStats>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getSavedContent' : ActorMethod<[], Array<SavedContent>>,
  'getSavedContentCount' : ActorMethod<[], bigint>,
  'getToolUsageCount' : ActorMethod<[string], bigint>,
  'getTotalUsageStats' : ActorMethod<
    [],
    { 'breakdown' : Array<ToolUsageStats>, 'totalUses' : bigint }
  >,
  'getTotalUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserStats>>,
  'listContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'recordToolUsage' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveContent' : ActorMethod<[SavedContent], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'unfavoriteTool' : ActorMethod<[string], undefined>,
  'updatePlan' : ActorMethod<[PlanType], undefined>,
  'updateProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];